# Generated by Django 4.0.10 on 2024-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('text_color', models.CharField(blank=True, choices=[('text-danger', 'red'), ('text-primary', 'blue'), ('text-success', 'green'), ('text-warning', 'yellow'), ('text-light', 'white'), ('text-dark', 'black')], max_length=50, null=True)),
                ('bg_color', models.CharField(blank=True, choices=[('bg-danger', 'red'), ('bg-primary', 'blue'), ('bg-success', 'green'), ('bg-warning', 'yellow'), ('bg-light', 'white'), ('bg-dark', 'black')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='workspaces', to='project.workspacecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
