# Generated by Django 4.0.10 on 2024-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='categories',
            field=models.ManyToManyField(related_name='workspaces', to='project.workspacecategory'),
        ),
    ]
